apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-green
  labels:
    app: petclinic
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
      color: green
  template:
    metadata:
      labels:
        app: petclinic
        color: green
    spec:
      containers:
      - name: petclinic
        image: wiiwake3101/spring-petclinic:latest
        ports:
        - containerPort: 8080