apiVersion: v1
kind: Service
metadata:
  name: petclinic-blue-service
spec:
  selector:
    app: petclinic
    color: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer