apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-blue
  labels:
    app: petclinic
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
      color: blue
  template:
    metadata:
      labels:
        app: petclinic
        color: blue
    spec:
      containers:
      - name: petclinic
        image: adarsh05122002/spring-petclinic:latest
        ports:
        - containerPort: 8080